package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	jsonPackage = protogen.GoImportPath("encoding/json")
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".tushare.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-tushare. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P() // 换行
	// 输出 package packageName
	g.P("package ", file.GoPackageName)
	g.P() // 换行

	g.P("var _ = ", jsonPackage.Ident("Decoder{}"))

	apiNameStr := ""
	fieldsStr := ""
	messageStr := ""

	for _, m := range file.Messages {
		fields := []string{}
		// message comment
		leadingComment := strings.TrimSuffix(m.Comments.Leading.String(), "\n")
		messageStr += m.Comments.Leading.String()

		// type struct
		messageStr += fmt.Sprintf("type %s struct {\n", m.GoIdent.GoName)

		for _, field := range m.Fields {
			trailingComment := strings.TrimSuffix(field.Comments.Trailing.String(), "\n")
			kind := field.Desc.Kind().String()

			// float类型
			if field.Desc.Kind() == protoreflect.FloatKind {
				kind = kind + "64"
			}

			// 一般情况
			inline := fmt.Sprintf("%s %s `json:\"%s\"` %s\n", field.GoName, kind, field.Desc.JSONName(), trailingComment)

			// message 类型
			if field.Desc.Kind() == protoreflect.MessageKind {
				inline = fmt.Sprintf("%s []*%s `json:\"%s\"` %s\n", field.GoName, field.Desc.Message().Name(), field.Desc.JSONName(), trailingComment)
			}

			messageStr += inline

			// fileds
			if !strings.Contains(m.GoIdent.GoName, "Request") && !strings.Contains(m.GoIdent.GoName, "Response") {
				fields = append(fields, "\""+field.Desc.JSONName()+"\"")
			}
		}

		messageStr += "}\n\n"

		if !strings.Contains(m.GoIdent.GoName, "Request") && !strings.Contains(m.GoIdent.GoName, "Response") {
			apiNameStr += fmt.Sprintf("%s api name\n", strings.Split(leadingComment, "|")[0])
			apiNameStr += fmt.Sprintf("const Api%s string = \"%s\"\n", m.Desc.Name(), strings.Split(leadingComment, "|")[1])
			fieldsStr += fmt.Sprintf("%s fields\n", strings.Split(leadingComment, "|")[0])
			fieldsStr += fmt.Sprintf("var Fields%s = []string{%s}\n", m.Desc.Name(), strings.Join(fields, ","))
		}

		if strings.Contains(m.GoIdent.GoName, "Response") {
			messageStr += fmt.Sprintf("func (x *%s) String() string {\n", m.GoIdent.GoName)
			messageStr += "bytes, _ := json.Marshal(x)\n"
			messageStr += "return string(bytes)\n"
			messageStr += "}\n"
		}
	}
	g.P("// api name")
	g.P()
	g.P(apiNameStr)
	g.P()
	g.P("// fields")
	g.P()
	g.P(fieldsStr)
	g.P()
	g.P("// struct")
	g.P()
	g.P(messageStr)
}
